name: BedWars1058
api-version: '1.13'
version: 1.1
author: andrei1058, YukiEnd
description: BedWars minigame Modified @ YukiEnd
main: com.andrei1058.bedwars.BedWars
softdepend: [ Vault,PlaceholderAPI,Parties,SlimeWorldManager,VipFeatures,Enhanced-SlimeWorldManager,PartyAndFriends,Spigot-Party-API-PAF ]
load: STARTUP
